# Generated by Django 2.2 on 2020-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('cutomer_address', models.TextField(blank=True, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
