# Generated by Django 2.2 on 2020-04-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200412_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_firm', models.CharField(max_length=100)),
                ('name_address1', models.CharField(max_length=200)),
                ('name_address2', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
