# Generated by Django 2.2 on 2020-04-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200413_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldoc',
            name='name_address1',
            field=models.CharField(max_length=100),
        ),
    ]
