# Generated by Django 2.2 on 2020-04-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200428_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alldoc',
            old_name='name_address1',
            new_name='name_Porduct',
        ),
        migrations.RenameField(
            model_name='alldoc',
            old_name='name_address2',
            new_name='name_idealprice',
        ),
    ]
