# Generated by Django 2.2 on 2020-04-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200428_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alldoc',
            old_name='name_idealprice',
            new_name='name_price',
        ),
    ]
