# Generated by Django 2.2 on 2020-04-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200428_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldoc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
