# Generated by Django 2.2 on 2020-06-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alldoc_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allcustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomer_id', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=100)),
                ('company', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('cutomer_address', models.TextField(blank=True, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='alldoc',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='alldoc',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='alldoc',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
